displayName=Anti Drag Blacklist
author=bop
description=Exclude configured items from RuneLite Anti Drag
tags=antidrag,delay,inventory,items,blacklist
plugins=com.bop.AntidragBlacklistPlugin
build=standard
